services:
  backend:
    build:
      context: ./backend
    network_mode: "host"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build:
      context: ./streamlit_frontend
    network_mode: "host"
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4